# Generated by Django 4.1.7 on 2023-06-27 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_alter_category_slug_alter_story_slug_alter_tag_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='description_az',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='title_az',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
