# Generated by Django 4.1.7 on 2023-07-01 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_category_name_az_category_name_en_category_name_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='stories',
        ),
        migrations.AddField(
            model_name='story',
            name='tag',
            field=models.ManyToManyField(to='blogs.tag'),
        ),
    ]
