# Generated by Django 4.1.7 on 2023-07-05 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_sponsor_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
    ]
