# Generated by Django 4.1.7 on 2023-06-28 21:09

from decimal import Decimal
from django.db import migrations
import djmoney.models.fields
import djmoney.models.validators


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_discount_product_product_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='money',
            field=djmoney.models.fields.MoneyField(decimal_places=1, default_currency='USD', max_digits=14, validators=[djmoney.models.validators.MinMoneyValidator(Decimal('0')), djmoney.models.validators.MaxMoneyValidator(Decimal('9999.989999999999781721271574497222900390625'))]),
        ),
    ]
