# Generated by Django 4.1.7 on 2023-06-28 21:11

from decimal import Decimal
from django.db import migrations
import djmoney.models.fields
import djmoney.models.validators


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_money'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='money',
            field=djmoney.models.fields.MoneyField(decimal_places=1, default_currency='USD', max_digits=14, validators=[djmoney.models.validators.MinMoneyValidator(Decimal('0')), djmoney.models.validators.MaxMoneyValidator(Decimal('9999.899999999999636202119290828704833984375'))]),
        ),
    ]
